import calabrese_broccoli from "../assets/Products/calabrese_broccoli.png";
import Banana from "../assets/Products/fresh_banana.png";
import WhiteNuts from "../assets/Products/white_nuts.png";
import RedTomato from "../assets/Products/vegan_red_tomato.png";
import MungBeans from "../assets/Products/mung_bean.png";
import BrownHazelnut from "../assets/Products/brown_hazelnut.png";
import EggsImg from "../assets/Products/eggs.png";
import ElaichiRusk from "../assets/Products/elaichi_rusk.png";
import Broccoli from "../assets/Products/broccoli.png";
import OnionImg from "../assets/Products/onion.png";
import CabbageImg from "../assets/Products/cabbage.png";

export const ProductsData = [
  {
    title: "Calabrese Broccoli",
    rating: 5,
    price: 20,
    new_price: 13,
    category: "Vegetable",
    imgsrc: calabrese_broccoli,
    featured: true,
    isOrganic: true,
    isFeaturedOrganic: false,
  },
  {
    title: "Fresh Bananas",
    rating: 5,
    price: 20,
    new_price: 14,
    category: "Fresh",
    imgsrc: Banana,
    featured: true,
    isOrganic: false,
    isFeaturedOrganic: false,
  },
  {
    title: "White Nuts",
    rating: 4.5,
    price: 20,
    new_price: 15,
    category: "Millets",
    imgsrc: WhiteNuts,
    featured: true,
    isOrganic: false,
    isFeaturedOrganic: false,
  },
  {
    title: "Vegan Red Tomatos",
    rating: 5,
    price: 20,
    new_price: 17,
    category: "Vegetable",
    imgsrc: RedTomato,
    featured: true,
    isOrganic: true,
    isFeaturedOrganic: true,
  },
  {
    title: "Mung Bean",
    rating: 5,
    price: 20,
    new_price: 11,
    category: "Health",
    imgsrc: MungBeans,
    featured: true,
    isOrganic: false,
    isFeaturedOrganic: false,
  },
  {
    title: "Brown Hezalnut",
    rating: 5,
    price: 20,
    new_price: 12,
    category: "Nuts",
    imgsrc: BrownHazelnut,
    featured: true,
    isOrganic: false,
    isFeaturedOrganic: false,
  },
  {
    title: "Eggs",
    rating: 5,
    price: 20,
    new_price: 17,
    category: "Fresh",
    imgsrc: EggsImg,
    featured: true,
    isOrganic: false,
    isFeaturedOrganic: false,
  },
  {
    title: "Zelco Suji Elaichi Rusk",
    rating: 5,
    price: 20,
    new_price: 15,
    category: "Fresh",
    imgsrc: ElaichiRusk,
    featured: true,
    isOrganic: false,
    isFeaturedOrganic: false,
  },
  {
    title: "Broccolie",
    rating: 5,
    price: 20,
    new_price: 15,
    category: "Vegetable",
    imgsrc: Broccoli,
    featured: false,
    isOrganic: true,
    isFeaturedOrganic: true,
  },
  {
    title: "Onion",
    rating: 4,
    price: 20,
    new_price: 17.5,
    category: "Vegetable",
    imgsrc: OnionImg,
    featured: false,
    isOrganic: true,
    isFeaturedOrganic: true,
  },
  {
    title: "Cabbage",
    rating: 4,
    price: 20,
    new_price: 14.5,
    category: "Vegetable",
    imgsrc: CabbageImg,
    featured: false,
    isOrganic: true,
    isFeaturedOrganic: true,
  },
];
